version: '3.8'

services:
  backend:
    container_name: ${BACKEND_IMAGE}
    image: ${BACKEND_IMAGE}
    ports:
      - "3000:3000"
    networks:
      - mern-network
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: always

  frontend:
    container_name: ${FRONTEND_IMAGE}
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    networks:
      - mern-network
    restart: always

  mongodb:
    container_name: ${DATABASE_IMAGE}
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo_data:/data/db
    restart: always

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
